//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : ai_db
	/// Data Source    : 192.168.1.91
	/// Server Version : 5.5.62-log
	/// </summary>
	public partial class AiDbDB : LinqToDB.Data.DataConnection
	{
		public ITable<连续图像> 连续图像 { get { return this.GetTable<连续图像>(); } }
		public ITable<图像>   图像   { get { return this.GetTable<图像>(); } }
		public ITable<文本>   文本   { get { return this.GetTable<文本>(); } }

		public AiDbDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AiDbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AiDbDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AiDbDB(DataOptions<AiDbDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("连续图像")]
	public partial class 连续图像
	{
		[PrimaryKey, Identity] public int    Id { get; set; } // int(11)
		[Column,     Nullable] public byte[] 数据 { get; set; } // longblob
		[Column,     Nullable] public string 标签 { get; set; } // varchar(256)
		[Column,     Nullable] public int?   状态 { get; set; } // int(11)
	}

	[Table("图像")]
	public partial class 图像
	{
		[PrimaryKey, Identity] public int    Id { get; set; } // int(11)
		[Column,     Nullable] public byte[] 数据 { get; set; } // longblob
		[Column,     Nullable] public string 标签 { get; set; } // varchar(256)
		[Column,     Nullable] public int?   状态 { get; set; } // int(11)
	}

	[Table("文本")]
	public partial class 文本
	{
		[PrimaryKey, Identity] public int    Id  { get; set; } // int(11)
		[Column,     Nullable] public string 提示词 { get; set; } // mediumtext
		[Column,     Nullable] public string 内容  { get; set; } // mediumtext
		[Column,     Nullable] public int?   状态  { get; set; } // int(11)
	}

	public static partial class TableExtensions
	{
		public static 连续图像 Find(this ITable<连续图像> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static 图像 Find(this ITable<图像> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static 文本 Find(this ITable<文本> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
